// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAGxFVS3UzaNoWZL0d6U3P0QtzKiVwVtaE',
    appId: '1:885144721672:web:6da59a42dfe855f4bbb4bd',
    messagingSenderId: '885144721672',
    projectId: 'firebase-auth-akashi',
    authDomain: 'fir-auth-akashi.firebaseapp.com',
    storageBucket: 'firebase-auth-akashi.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCPLLU-F0LkxoKlMrKz7v2lSk03xmvWzFU',
    appId: '1:885144721672:android:a0d2652c9cd19c9abbb4bd',
    messagingSenderId: '885144721672',
    projectId: 'firebase-auth-akashi',
    storageBucket: 'firebase-auth-akashi.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCKQESrIFuUzRGAN7oRvv1PA9DlgujTdC0',
    appId: '1:885144721672:ios:0fc58d7e28172fc9bbb4bd',
    messagingSenderId: '885144721672',
    projectId: 'firebase-auth-akashi',
    storageBucket: 'firebase-auth-akashi.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCKQESrIFuUzRGAN7oRvv1PA9DlgujTdC0',
    appId: '1:885144721672:ios:0fc58d7e28172fc9bbb4bd',
    messagingSenderId: '885144721672',
    projectId: 'firebase-auth-akashi',
    storageBucket: 'firebase-auth-akashi.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAGxFVS3UzaNoWZL0d6U3P0QtzKiVwVtaE',
    appId: '1:885144721672:web:ec8c79e8fc32ab8bbbb4bd',
    messagingSenderId: '885144721672',
    projectId: 'firebase-auth-akashi',
    authDomain: 'fir-auth-akashi.firebaseapp.com',
    storageBucket: 'firebase-auth-akashi.appspot.com',
  );
}
